### ISSUE TITLE
Testing on H36M

### ISSUE THREAD

**Issue by jamalknight** [Samleo8/learnable-triangulation-pytorch#1]
You mentioned that there was code provided to test the 'learnable triangulation' algorithm on H36M, but I could not find it on their github page, could you please point out to where it is?

Thanks

**Comment by Samleo8** [comment]
https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md

**Comment by jamalknight** [comment]
thanks
